site_name: McLaren Synth Kit
google_analytics: ['G-L0L8TCDS1C', 'mclarenlabs.github.io']
nav:
  - Introduction: 'index.md'
  - GNUstep and VSCode: 'setup.md'
  - Chapters:
    - Alsa Sound Kit - MIDI: 'ask-midi.md'
    - Alsa Sound Kit - PCM: 'ask-pcm.md'
    - Mclaren Synth Kit - Overview: 'msk-over.md'
    - Conclusion: 'conclusion.md'
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - console
    - objc
    - yaml
  shortcuts:
    help: 191     # ?
    next: 78      # n
    previous: 80  # p
    search: 83    # s
